### ISSUE TITLE
Move to a new home?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/socket2-rs#116]
@Thomasdezeeuw @stjepang y'all have been doing a great job maintaining this crate, and I clearly don't have time for it, so I was wondering if y'all would prefer it live somewhere else? I don't think it's helping much living under my name right now!

**Comment by Thomasdezeeuw** [comment]
I'm fine with moving it. Perhaps it could live under the Tokio organisation to give some more exposure. I plan to move Mio to use socket2 in the long term.

@stjepang what do you think?

**Comment by stjepang** [comment]
I also don't have time to keep working on this crate but would very strongly recommend **not** moving it into Tokio.

Instead, move socket2 into your personal account or create a new GitHub organization for it. Or, even better: there are good chances socket2 would be accepted by the rust-lang organization. I think that would be the healthiest decision for Rust and Open Source.

Cheers and good luck! <3

**Comment by stjepang** [comment]
I also don't have the time to keep working on this crate. Up to you!

**Comment by Thomasdezeeuw** [comment]
I would be OK with moving socket2 into the rust-lang organisation. My full plan for socket2 is the following:

* Medium term: turn socket2 into the socket library for all Rust crates not using std lib sockets.
* Medium term: change Mio to use socket2 and provide good integration with it.
* Long term: change the std lib implementation to be based on socket2, providing additional methods on TcpStream/TcpListener/UdpSocket.

I do expect this to take a couple of years however.

@alexcrichton I think you're the most experienced with moving crates into the rust-lang organisation, do you think socket2 would be accepted?

**Comment by alexcrichton** [comment]
I'm not sure, [let's find out](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/socket2.20in.20rust-lang.3F)

**Comment by alexcrichton** [comment]
Ok moved to rust-lang now!

@Thomasdezeeuw let me know if any permissions look awry, but I think you should be good to go!
