### ISSUE TITLE
Socket::keepalive doesn't work on Windows

### ISSUE THREAD

**Issue by sfackler** [rust-lang/socket2-rs#24]
There is apparently not any way of reading these values.

**Comment by alexcrichton** [comment]
Weird, does the ioctl we execute do anything at all?

And for posterity I think the relevant test which is the impetus for this is here:

https://github.com/alexcrichton/socket2-rs/blob/f1952af36473cbd0934a660fde2f0851c5941033/src/socket.rs#L974-L984

**Comment by sfackler** [comment]
It fails because the input pointer is invalid.

**Comment by YorickPeterse** [comment]
I also ran into this issue. When obtaining the keepalive value, an error is returned with the following message:

> The system detected an invalid pointer address in attempting to use a pointer argument in a call. (os error 10014)

Unfortunately, I know next to nothing about the winsocks API so I'm not sure how to determine what the root cause is, and how to fix it.

**Comment by hawkw** [comment]
I did some research, and as far as I can tell, [the Microsoft documentation doesn't make any mention of accessing the keepalive values using `WSAIoctl`, or via any other function](https://docs.microsoft.com/en-us/windows/win32/winsock/sio-keepalive-vals). However, it never clearly states that this is _not_ possible.

The closest thing to a definitive answer I could find is [this StackOverflow answer](https://stackoverflow.com/questions/14197347/how-to-query-socket-keep-alive-values-using-winsock/14198462#14198462) (admittedly, not the *most* reliable source), which states:
> The system doesn't have any method of checking the current values of the `tcp_keepalive` structure passed to `WSAIoctl` for `SIO_KEEPALIVE_VALS`. You can set them to the values you want, but you cannot interrogate what they are presently.

Of course, it's still possible to test whether or not keepalive is _enabled_ for a socket on Windows, by using `getsockopt(SOL_SOCKET, SO_KEEPALIVE, ...)`, as one would on Linux. However, it's not possible to retrieve the keepalive _time_. The only good solution I can think of is splitting the API into two methods, one of which returns a bool indicating whether or not TCP keepalive is enabled, and another which returns the configured keepalive idle duration. The second would have to be `#[cfg(not(windows))]`.
