### ISSUE TITLE
Support for IP_FREEBIND on Linux

### ISSUE THREAD

**Issue by bdonlan** [rust-lang/socket2-rs#90]
It would be useful to be able to set the IP_FREEBIND socket option that is available on linux.

See also https://github.com/rust-lang/libc/pull/1835 for exposing this symbol from libc.

**Comment by Thomasdezeeuw** [comment]
Sounds good to me. Could you add a `cfg` similar to: https://github.com/alexcrichton/socket2-rs/blob/25f2949fd7b7ab93907f33d8f9b0eb0d7baafadb/src/sys/unix.rs#L92
